name: lint-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
      BETTER_AUTH_URL: http://localhost:3000

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Generate prisma client
        run: npx prisma generate
      
      - name: Debug Prisma Output Path
        run: |
          echo "---"
          find . -type d -name "prisma" | grep generated
          echo "---"
          ls -la src/generated/prisma 
          echo "---"

      - name: Push schema
        run: npx prisma db push 

      - name: Seeding db
        run: npx prisma db seed

      - name: Test
        if: always()
        run: npm test       
